### ISSUE TITLE
CPU 占有很高

### ISSUE THREAD

**Issue by qwerOC** [Jonhory/LiveSendGift#11]
在加载本地gif的时候cpu会暴增 <使用YYimage加载>
使用<SDwebimage> 时内存会暴增

**Comment by Jonhory** [comment]
有尝试过使用别的框架加载GIF吗

**Comment by qwerOC** [comment]
使用webp格式的图片没有这个问题 其他的框架都不行




| |
邮箱：lv19961110@163.com
|

签名由 网易邮箱大师 定制

在2018年05月04日 17:48，Jonhory 写道：

有尝试过使用别的框架加载GIF吗

**Comment by atom2ueki** [comment]
@Jonhory 这个lib如果不需要点击事件，也许可以通过用CALayer来显示图片,label 等
