### ISSUE TITLE
送的礼物过多以后，就不显示了

### ISSUE THREAD

**Issue by tulermos** [Jonhory/LiveSendGift#12]
我这边是个直播项目，然后送的礼物次数到达一定次数以后最上面那一行就不显示动画了，然后是第二行不显示，最后整个都不显示了。

**Comment by Jonhory** [comment]
请问能提供一个demo看看吗

**Comment by tulermos** [comment]
NSDate* date = [NSDate dateWithTimeIntervalSinceNow:0];
                        NSTimeInterval a=[date timeIntervalSince1970]*1000; // *1000 是精确到毫秒，不乘就是精确到秒
                        NSString *timeString = [NSString stringWithFormat:@"%.0f", a]; //转为字符型
                        _sendUserModel = [LiveUserModel new];
                        _sendUserModel.name =dic[@"nick_name"];
                        _sendUserModel.iconUrl = dic[@"head_icon"];
                        _sendUserModel.timeStr =timeString;
                        LiveGiftListModel * model = [LiveGiftListModel new];
                        model.name = dic[@"gift_name"];
                        model.personSort = dic[@"gift_name"];
                        model.picUrl = dic[@"gift_img"];
                        model.rewardMsg = [NSString stringWithFormat:@"送出%@",dic[@"gift_name"]];
                        model.background_img =[NSString stringWithFormat:@"%@",dic[@"background_img"]];
                        LiveGiftShowModel * showmodel = [LiveGiftShowModel giftModel:model userModel:_sendUserModel];
                        [self.customGiftShow addLiveGiftShowModel:showmodel showNumber:[dic[@"number"] integerValue]];这是代码，这是在收到礼物消息的时候才会执行。

**Comment by cdpenggod** [comment]
> 我这边是个直播项目，然后送的礼物次数到达一定次数以后最上面那一行就不显示动画了，然后是第二行不显示，最后整个都不显示了。

咱俩应该碰到一样问题，是作者忽略了被替换的model，我已经提了pull request，你可以看下，应该可以解决

**Comment by Jonhory** [comment]
根据描述，我无法重现问题，所以一直拖着。看了你的PR，觉得思路是对的。
