### ISSUE TITLE
老哥，有swift版本吗？

### ISSUE THREAD

**Issue by hewang1016729378** [Jonhory/LiveSendGift#18]

**Comment by Jonhory** [comment]
没有哦，在计划中，但是还没决定用swift重写。

**Comment by hewang1016729378** [comment]
Oc的版本没有pod的吗？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Jonhory <notifications@github.com&gt;
发送时间: 2020年8月22日 13:51
收件人: Jonhory/LiveSendGift <LiveSendGift@noreply.github.com&gt;
抄送: hewang1016729378 <1016729378@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[Jonhory/LiveSendGift] 老哥，有swift版本吗？ (#18)





 
没有哦，在计划中，但是还没决定用swift重写。

**Comment by Jonhory** [comment]
没有，因为需要开发者自行修改UI相关代码。
