### ISSUE TITLE
内存释放问题

### ISSUE THREAD

**Issue by gxtai** [Jonhory/LiveSendGift#20]
![image](https://user-images.githubusercontent.com/52225007/122740442-8b6d2980-d2b6-11eb-97ab-ab5eb6b58403.png)

![image](https://user-images.githubusercontent.com/52225007/122740475-945dfb00-d2b6-11eb-832d-76f035857a99.png)

父视图消失后，定时器应该停止

**Comment by Jonhory** [comment]
感谢。
