### ISSUE TITLE
【Bug】点击first,fourth,fifth，然后再点击third, 显示有问题

### ISSUE THREAD

**Issue by AbnerPei** [Jonhory/LiveSendGift#21]
①：点击first,fourth,fifth，然后再快递点击third，third显示从1开始

②：点击first,fourth,fifth，然后再点击third一次，然后再快速点击third多次，third显示从99开始，然后累加了起来

**Comment by Jonhory** [comment]
当最新的任务需要展示固定数字
`addLiveGiftShowModel:showNumber`
且不存在旧模型
`!oldShowView || ![oldShowView isKindOfClass:[LiveGiftShowView class]]`
且当前弹幕数量大于最大限制
`self.showViewArr.count >= live_maxGiftShowCount`
则加入队列，此时未考虑到`showNumber`
`addToQueue:`

在`fix/show_number`分支修复
