### ISSUE TITLE
你这边为什么是0.01

### ISSUE THREAD

**Issue by hongtianpei1990gmail** [Jonhory/LiveSendGift#8]
![image](https://user-images.githubusercontent.com/17697229/29400429-f9bce8b2-835f-11e7-8249-d67d934b3283.png)

**Comment by Jonhory** [comment]
可以试着给一个值，比如200，然后给个背景颜色。这里我想的是弹幕视图不需要响应用户的点击事件且不会遮挡后面的视图点击事件。
